openapi: 3.0.0
info:
  title: Todo App Authentication API
  version: 1.0.0
  description: API contracts for authentication and authorization endpoints

paths:
  /api/auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  token:
                    type: string
        '400':
          description: Invalid input
        '409':
          description: User already exists

  /api/auth/login:
    post:
      summary: Authenticate user and return JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user_id:
                    type: string
        '401':
          description: Invalid credentials

  /api/{user_id}/tasks:
    get:
      summary: Get user's tasks
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user's tasks
        '401':
          description: Unauthorized - missing or invalid token
        '403':
          description: Forbidden - token user_id doesn't match path user_id
    post:
      summary: Create a new task for user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Task created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - token user_id doesn't match path user_id

  /api/{user_id}/tasks/{task_id}:
    get:
      summary: Get specific task
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Task details
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - token user_id doesn't match path user_id
        '404':
          description: Task not found
    put:
      summary: Update specific task
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                completed:
                  type: boolean
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Task updated
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - token user_id doesn't match path user_id
        '404':
          description: Task not found
    delete:
      summary: Delete specific task
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Task deleted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - token user_id doesn't match path user_id
        '404':
          description: Task not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT